export { Home } from './Home/Home'
export { Login } from './Login/Login'
export { Signup } from './Signup/Signup'
export { Quiz } from './Quiz/Quiz'
export { Result } from '../Result/Result'
export { AboutUs } from './AboutUs/AboutUs'